name: vpsrun
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install neofetch -y
      - run: curl -sSf https://sshx.io/get | sh -s run
